version: "3.8"

services:
  pdf-watcher:
    image: polyhydra/poppler-watcher:1.2
    volumes:
      - /volume1/docker/pdf:/work
    environment:
      - INPUT_DIR=/work/in
      - OUTPUT_DIR=/work/out
      - ARCHIVE_DIR=/work/archive
      - FAILED_DIR=/work/failed
      - STABLE_SECONDS=2

      # Do both: clean page renders + organized raw assets
      - MODE=both
      - RENDERER=pdftocairo
      - DPI=300

      # Filtering / bucketing for extracted assets:
      - MIN_W=32
      - MIN_H=32
      - MIN_PIXELS=10000
      - BLANK_MAX_NONWHITE_PCT=0.5

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10

      # If /volume1 exists only on a specific Swarm node, pin it:
      # placement:
      #   constraints:
      #     - node.hostname == nas-node
